### ISSUE TITLE
what is TopoMap pos parameter?

### ISSUE THREAD

**Issue by DunkHimYo** [Nikeshbajaj/spkit#2]
I've seen this TopoMap in example but pos parameter is not init.. how can I use this?

**Comment by DunkHimYo** [comment]
Oh i found it from spkit.eeg import pos

**Comment by Nikeshbajaj** [comment]
import spkit as sp
Yes, indeed, for 14-channel, you can use it like 
pos = sp.eeg.pos
ch_names = sp.eeg.ch_names

However, for different channels and a few selected channels, you can extract pos as

ch_names = ['AF3','F7','F3','FC5','T7','P7','O1','O2','P8','T8','FC6','F4','F8','AF4']
pos, ch1 = sp.eeg.s1020_get_epos2d_(ch_names, reorder=False)
