### ISSUE TITLE
IndexError: index 2048 is out of bounds for axis 0 with size 2048

### ISSUE THREAD

**Issue by mkhazova** [Nikeshbajaj/spkit#9]
Hi. Thanks for your great job!
I try to run your code (Generating Dynamic Spatio-Spectral Map) and have this error:
-->  ax2.set_xlim([tx[i],tx[i+3*N]])
_IndexError: index 2048 is out of bounds for axis 0 with size 2048_

Also I have no interactive wiget.

**Comment by Nikeshbajaj** [comment]
Hi, 

It seems like your tx array is shoter than 2048.

**Comment by Nikeshbajaj** [comment]
It was indeed a bug in the code,

Now it is fixed  - https://github.com/spkit/spkit.github.io/commit/864565c6f6f1b0cf9644fface85f4d9f7280efca

Updated code is here!

[https://spkit.github.io/examples/gen_topo](https://spkit.github.io/examples/gen_topo)
